// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace avanphamaceuticalsmanagement.Shared.Models;

[Table("BudgetTypeTable")]
public partial class BudgetTypeTable
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string BudgetType { get; set; }

    [InverseProperty("BudgetType")]
    public virtual ICollection<BudgetsTable> BudgetsTables { get; } = new List<BudgetsTable>();
}