// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace avanphamaceuticalsmanagement.Shared.Models;

[Table("BudgetsTable")]
public partial class BudgetsTable
{
    [Key]
    public int id { get; set; }

    public int? BudgetTypeId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? StartDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EndDate { get; set; }

    [Unicode(false)]
    public string Comment { get; set; }

    public double? Amount { get; set; }

    [ForeignKey("BudgetTypeId")]
    [InverseProperty("BudgetsTables")]
    public virtual BudgetTypeTable BudgetType { get; set; }
}