// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace avanphamaceuticalsmanagement.Shared.Models;

[Table("DrugStockTable")]
public partial class DrugStockTable
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string DrugName { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string DrugCode { get; set; }

    public double? Price { get; set; }

    public int? Quantity { get; set; }

    [Unicode(false)]
    public string Description { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Unit { get; set; }

    public double? OrderPrice { get; set; }

    public int? DrugCat { get; set; }

    [ForeignKey("DrugCat")]
    [InverseProperty("DrugStockTables")]
    public virtual Drugcategory DrugCatNavigation { get; set; }

    [InverseProperty("Drug")]
    public virtual ICollection<PharmacyTransactionsTable> PharmacyTransactionsTables { get; } = new List<PharmacyTransactionsTable>();
}