// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace avanphamaceuticalsmanagement.Shared.Models;

[Table("ExpensesTable")]
public partial class ExpensesTable
{
    [Key]
    public int Id { get; set; }

    public int? ExpenseTypeID { get; set; }

    public double? Amount { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Date { get; set; }

    [ForeignKey("ExpenseTypeID")]
    [InverseProperty("ExpensesTables")]
    public virtual ExpenseTypesTable ExpenseType { get; set; }
}