// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace avanphamaceuticalsmanagement.Shared.Models;

[Table("PharmacyTransactionsTable")]
public partial class PharmacyTransactionsTable
{
    [Key]
    public int Id { get; set; }

    public int? PatientId { get; set; }

    public int? DrugId { get; set; }

    public int? PrescribedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Date { get; set; }

    public double saleAmout { get; set; }

    public int? Quantity { get; set; }

    public int? StockCategoryId { get; set; }

    public int? AgrovetId { get; set; }

    public int? CosmeticId { get; set; }

    public int? DrugCategoryId { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Condition { get; set; }

    public int? CustomerTypeID { get; set; }

    [ForeignKey("AgrovetId")]
    [InverseProperty("PharmacyTransactionsTables")]
    public virtual AgrovetStockTable Agrovet { get; set; }

    [ForeignKey("CosmeticId")]
    [InverseProperty("PharmacyTransactionsTables")]
    public virtual CosmeticsStockTable Cosmetic { get; set; }

    [ForeignKey("CustomerTypeID")]
    [InverseProperty("PharmacyTransactionsTables")]
    public virtual CustomerTypeTable CustomerType { get; set; }

    [ForeignKey("DrugId")]
    [InverseProperty("PharmacyTransactionsTables")]
    public virtual DrugStockTable Drug { get; set; }

    [ForeignKey("DrugCategoryId")]
    [InverseProperty("PharmacyTransactionsTables")]
    public virtual Drugcategory DrugCategory { get; set; }

    [ForeignKey("PatientId")]
    [InverseProperty("PharmacyTransactionsTables")]
    public virtual PatientsTable Patient { get; set; }

    [ForeignKey("PrescribedBy")]
    [InverseProperty("PharmacyTransactionsTables")]
    public virtual EmployeesTable PrescribedByNavigation { get; set; }

    [ForeignKey("StockCategoryId")]
    [InverseProperty("PharmacyTransactionsTables")]
    public virtual StockCategoryTable StockCategory { get; set; }
}