// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace avanphamaceuticalsmanagement.Shared.Models;

[Table("PharmacyTransactionsTable")]
public partial class PharmacyTransactionsTable
{
    [Key]
    public int Id { get; set; }

    public int? PatientId { get; set; }

    public int? DrugId { get; set; }

    public int? PrescribedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Date { get; set; }

    public double saleAmout { get; set; }

    public int? Quantity { get; set; }

    [ForeignKey("DrugId")]
    [InverseProperty("PharmacyTransactionsTables")]
    public virtual DrugStockTable Drug { get; set; }

    [ForeignKey("PatientId")]
    [InverseProperty("PharmacyTransactionsTables")]
    public virtual PatientsTable Patient { get; set; }

    [ForeignKey("PrescribedBy")]
    [InverseProperty("PharmacyTransactionsTables")]
    public virtual EmployeesTable PrescribedByNavigation { get; set; }
}