// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace avanphamaceuticalsmanagement.Shared.Models;

[Table("RestockRequestsTable")]
public partial class RestockRequestsTable
{
    [Key]
    public int Id { get; set; }

    public int? RequestCategoryId { get; set; }

    public int? RequestDrugCategoryId { get; set; }

    public int? RequestDrugId { get; set; }

    public int? RequestAgrovetId { get; set; }

    public int? RequestBabyProductsId { get; set; }

    public int? RequestGeneralItemsId { get; set; }

    public int? RequestCosmeticId { get; set; }

    public int? Quantity { get; set; }

    public double? OrderPrice { get; set; }

    public int? Status { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Requester { get; set; }

    [ForeignKey("RequestCategoryId")]
    [InverseProperty("RestockRequestsTables")]
    public virtual StockCategoryTable RequestCategory { get; set; }

    [ForeignKey("RequestCosmeticId")]
    [InverseProperty("RestockRequestsTables")]
    public virtual CosmeticsStockTable RequestCosmetic { get; set; }

    [ForeignKey("RequestDrugId")]
    [InverseProperty("RestockRequestsTables")]
    public virtual DrugStockTable RequestDrug { get; set; }

    [ForeignKey("RequestDrugCategoryId")]
    [InverseProperty("RestockRequestsTables")]
    public virtual Drugcategory RequestDrugCategory { get; set; }

    [ForeignKey("Status")]
    [InverseProperty("RestockRequestsTables")]
    public virtual RestockStatusTable StatusNavigation { get; set; }
}