// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using avanphamaceuticalsmanagement.Shared.Models;

using Microsoft.EntityFrameworkCore;

namespace AvanPharmacyDomain.Data;

public partial class avanpharmacyDbContext : DbContext
{
    public avanpharmacyDbContext(DbContextOptions<avanpharmacyDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<DeviceCode> DeviceCodes { get; set; }

    public virtual DbSet<DrugStockTable> DrugStockTables { get; set; }

    public virtual DbSet<EmployeesTable> EmployeesTables { get; set; }

    public virtual DbSet<PatientsTable> PatientsTables { get; set; }

    public virtual DbSet<PersistedGrant> PersistedGrants { get; set; }

    public virtual DbSet<PharmacyTransactionsTable> PharmacyTransactionsTables { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<PharmacyTransactionsTable>(entity =>
        {
            entity.HasOne(d => d.Drug).WithMany(p => p.PharmacyTransactionsTables).HasConstraintName("FK_PharmacyTransactionsTable_DrugStockTable");

            entity.HasOne(d => d.Patient).WithMany(p => p.PharmacyTransactionsTables).HasConstraintName("FK_PharmacyTransactionsTable_PatientsTable");

            entity.HasOne(d => d.PrescribedByNavigation).WithMany(p => p.PharmacyTransactionsTables).HasConstraintName("FK_PharmacyTransactionsTable_PharmacyTransactionsTable");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}